# TL;DR
# docker-compose -f docker-compose.listener.yml up

version: '2.3'

services:

  listener:
    build: .
    command: ros2 run demo_nodes_cpp listener

  talker:
    build: .
    command: ros2 run demo_nodes_cpp talker